name: suco_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  onesignal_flutter: ^5.2.0
  audioplayers: ^6.0.0
  webview_flutter: ^4.7.0
  table_calendar: ^3.0.9
  video_player: ^2.8.6
  chewie: ^1.7.5
  flutter_html: ^3.0.0-beta.2
  just_audio: ^0.9.37
  audio_video_progress_bar: ^1.0.1
  vimeo_video_player: ^0.0.8
  image_picker: ^1.0.4
  share_plus: ^7.2.1
  qr_flutter: ^4.1.0
  qr_code_scanner: ^1.0.1
  supabase_flutter: ^2.5.6
  cupertino_icons: ^1.0.8
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/Suco-DarkGreyIcon.png
    - assets/images/venn.png
    - assets/images/sucolive.png
    - assets/images/wellnessbot.jpg
    - assets/images/bg-image.jpeg
    - assets/images/carousel1.jpeg
    - assets/images/carousel2.jpeg
    - assets/images/hero-section.jpeg
    - assets/images/active-meditation.jpeg
    - assets/images/sleep-ritual.jpeg
    - assets/images/soundscape.jpeg
    - assets/images/breathwork-session.jpeg
    - assets/images/challenge_full.jpeg
    - assets/images/Suco-Lime.png
    - assets/fonts/

  fonts:
    - family: BDOGrotesk
      fonts:
        - asset: assets/fonts/BDOGrotesk-Regular.ttf

    - family: NeueHaasUnica
      fonts:
        - asset: assets/fonts/Neue Haas Unica W1G Heavy.ttf
          weight: 800

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
